import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/common/components/Navbar";
import ReactQueryProvider from "./_providers/ReactQueryProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Mazaady Task",
	description: "Generated by create next app",
	icons: "https://mazaady.com/images/mazaady-logo.svg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				lang="en"
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReactQueryProvider>
					<div className="fixed top-0 left-0 w-full ">
						<Navbar />
					</div>
					{children}
				</ReactQueryProvider>
			</body>
		</html>
	);
}
